//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrigGoogleMapApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrigGoogleMapApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Events o events
        ///google.maps.event.addDomListener(window, &apos;load&apos;, initialize);.
        /// </summary>
        internal static string GoogleMapEventsFunction {
            get {
                return ResourceManager.GetString("GoogleMapEventsFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function initialize() {
        ///
        ///
        ///
        ///    var haightAshbury = new window.google.maps.LatLng(37.7699298, -122.4469157);
        ///    var mapOptions = {
        ///        zoom: 12,
        ///        center: haightAshbury,
        ///        mapTypeId: window.google.maps.MapTypeId.TERRAIN
        ///    };
        ///    map = new window.google.maps.Map(document.getElementById(&quot;map_canvas&quot;), mapOptions);
        ///
        ///    for (var i = 0; i &lt; latlngArray.length; i++) {
        ///        addMarker(latlngArray[i], titleArray[i]);
        ///    }
        ///
        ///}
        ///
        ///
        ///function addMarker(location, markerTitle) {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoogleMapFunction {
            get {
                return ResourceManager.GetString("GoogleMapFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var map;
        ///var markersArray = [];
        ///var latlngArray = [];//LatLongs
        ///var titleArray = [];//Titles.
        /// </summary>
        internal static string GoogleMapGlobalVariables {
            get {
                return ResourceManager.GetString("GoogleMapGlobalVariables", resourceCulture);
            }
        }
    }
}
